[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Monad Testnet
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143
solc_version = "0.8.28"
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
